### PR TITLE
Page for the job ad for a customer service team member.

### PR DESCRIPTION
**Pull request by Kusti**

### CODE REVIEW

**Comment by thomasmalbaux** [comment]
Not sure how it works exactly but cool if you can make it a page (in \src\html\pages) instead of an .html file ;-)

Also good to add to marketing-site\src\sitemap.xml

**Comment by Kusti** [comment]
@thomasmalbaux hmm, a good point about removing the .html. One thing I'm wondering is whether it makes sense, since jobs page is now an HTML file. Actually jobs should be the folder and this one under it, but then we would need to do the redirect, and I'm not sure how that works... but that would be much better.

**Comment by thomasmalbaux** [comment]
(if in the process you find an easy way to build 301 redirections I'd be happy to hear it as I have quite a few of them I'd like to add to manage 404 and redirect incorrect incoming traffic)

**Comment by Gnito** [comment]
I think those source codes looks OKish. You haven't added any new styles there? 
Generic styles for pure tags are usually a bit risky since their style might change at some point.

**Comment by Kusti** [comment]
@Gnito no, didn't add styles, I used the ones that the main Jobs page uses - lazy :( should I change them, do you think it's important?

**Comment by Kusti** [comment]
Or can I merge?

**Pull request merged**
